version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:${KAFKA_VERSION}
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker-1:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    container_name: broker-1
    ports:
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-1:9092,PLAINTEXT_INTERNAL://localhost:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  broker-2:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    container_name: broker-2
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-2:9092,PLAINTEXT_INTERNAL://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:${KAFKA_VERSION}
    container_name: schema-registry
    depends_on:
      - broker-1
      - broker-2
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker-1:9092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  kafka-setup:
    image: confluentinc/cp-kafka:${KAFKA_VERSION}
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      kafka-topics --bootstrap-server broker-1:9092 --list # blocks until kafka is reachable
      
      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server broker-1:9092 --create --if-not-exists --topic payment-request --replication-factor 2 --partitions 2
      kafka-topics --bootstrap-server broker-1:9092 --create --if-not-exists --topic payment-response --replication-factor 2 --partitions 2
      kafka-topics --bootstrap-server broker-1:9092 --create --if-not-exists --topic restaurant-approval-request --replication-factor 2 --partitions 2
      kafka-topics --bootstrap-server broker-1:9092 --create --if-not-exists --topic restaurant-approval-response --replication-factor 2 --partitions 2
      kafka-topics --bootstrap-server broker-1:9092 --create --if-not-exists --topic customer --replication-factor 2 --partitions 2
      
      
      echo -e 'Successfully created the next topics:'
      kafka-topics --bootstrap-server broker-1:9092 --list
      "
  kafka-manager:
    image: sheepkiller/kafka-manager:stable
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - kafka-setup
    environment:
      ZK_HOSTS: "zookeeper:2181"

